global_costmap:
   global_frame: map                 # 全局坐标系，一般设置为map
   robot_base_frame: agv_base_link    # 移动机器人基座坐标系
   transform_tolerance: 1.0           # tf的延时，默认0.2s
   update_frequency: 5.0              # 地图更新的频率，默认为5Hz
   publish_frequency: 1.0             # 地图发布的频率，如在rviz中显示，默认为0Hz
   static_map: true                   # 使用预先加载的地图，该值为true时，rolling_window一定为false
  #  track_unknown_space: true
  #  rolling_window: false              # 使用rolling_window地图，默认为false
  #  当static_map为true时，这些参数通过加载的map覆盖
  #  resolution:
  #  width:
  #  height:
  #  orgin_x:
  #  orgin_y:

   plugins:
     - {name: static_layer,            type: "costmap_2d::StaticLayer"}
     - {name: obstacle_layer,          type: "costmap_2d::ObstacleLayer"}
     - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
