mm_joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  

arm_joint_group_controller:
  type: "position_controllers/JointGroupPositionController"
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint

agv_joint_group_controller:
  type: "position_controllers/JointGroupPositionController"
  joints:
    - x_joint
    - y_joint
    - angle_joint